spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Techni
    username: postgres
    password: 19410719
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      show-sql: true
#    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true

#
#spring:
#  datasource:
#    url: jdbc:h2:mem:techni
#    driver-class-name: org.h2.Driver
#    username: sa
#    password: 1234
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#  h2:
#    console:
#      enabled: true
